<?php

/**
 * PluginsmaugvSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsmaugvSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsmaugvSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsmaugvSlot');
    }
}